# Generated by Django 2.2.2 on 2023-04-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='owner_name',
            new_name='user_name',
        ),
    ]
